# Compiler
CXX = g++

# Compiler flags
CXXFLAGS = -I"D:/Mustafa/Habib/OOP/OOP-Project/" -I"C:/mingw_dev_lib/include"

# Linker flags
LDFLAGS = -L"C:/mingw_dev_lib/lib" -lsfml-graphics -lsfml-window -lsfml-system

# Source files
SOURCES = Main.cpp \
          gameLayer/code/MainMenu.cpp \
          gameLayer/code/world.cpp \
          gameLayer/code/sprites.cpp

# Object files
OBJECTS = $(SOURCES:.cpp=.o)

# Executable name
EXECUTABLE = my_program.exe

# Default target
all: $(EXECUTABLE)

# Link the executable
$(EXECUTABLE): $(OBJECTS)
	$(CXX) $(OBJECTS) -o $@ $(LDFLAGS)

# Compile source files to object files
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Clean up build files
clean:
	rm -f $(OBJECTS) $(EXECUTABLE)